# Spawn location
spawn_x: 0.5
spawn_y: 10.0
spawn_z: 0.5

spawn_yaw: 0
spawn_pitch: 0

# KOTL
kotl_enabled: true

kotl_x: 25
kotl_z: 11

kotl_score_height_min: 10000
kotl_score_height_max: 10000

kotl_radius: 5

ktol_hologram:
    enabled: true
    lines: 10
    x: 10000.5
    y: 0
    z: 10000.5

# Lobby leaderboard
lobby_player_leaderboard:
    x: 0.0
    y: 0.0
    z: 0.0

lobby_team_leaderboard:
    x: 0.0
    y: 0.0
    z: 0.0

hall_of_fame:
    enabled: false
    stats_url: "https://novauniverse.net/api/mcf/result/"
    debug: false
    name_hologram_location:
       x: 0
       y: 0
       z: 0

prevent_damage_mobs: false