main: net.novauniverse.mctournamentsystem.lobby.TournamentSystemLobby
name: TournamentSystemLobby
description: h
version: 1.0
api-version: 1.13

depend: [NovaCore, HolographicDisplays, ProtocolLib, TitleAPI, TournamentSystem, Citizens]
softdepent: [NovaCoreGameEngine]
loadbefore: [NovaGamesTarget]