main: net.novauniverse.mctournamentsystem.spigot.resourcepackmanager.TournamentSystemResourcePackManager
name: TournamentSystemResourcePackManager
description: NOW WITH RESOURCE PACKS UwU
version: 1.0
api-version: 1.13

authors: [Zeeraa, NovaUniverse]

depend: [NovaCore, TournamentSystem]