main: net.novauniverse.mctournamentsystem.missilewars.lobby.MissileWarsLobby
name: MissilewarsLobby
description: h
version: 1.0
api-version: 1.13

authors: [Zeeraa, NovaUniverse]

depend: [NovaCore, DecentHolograms, ProtocolLib, TitleAPI, NovaMissileWars]
softdepent: [NovaCoreGameEngine]
loadbefore: [NovaGamesTarget]