main: net.novauniverse.mctournamentsystem.spigot.TournamentSystem
name: TournamentSystem
description: The 4th version of the tournament system developed by novauniverse
version: 1.0
api-version: 1.13

authors: [Zeeraa, NovaUniverse]

depend: [NovaCore, HolographicDisplays, ProtocolLib, TitleAPI, LuckPerms, Citizens, NoteBlockAPI]
softdepend: [NovaCoreGameEngine, LabyApi, ItemsAdder]
loadbefore: [NovaGamesTarget, NovaSurvivalGames, ChickenOut, HolographicPlaceholders]