main: net.novauniverse.mctournamentsystem.spigot.TournamentSystem
name: TournamentSystem
description: The 4th version of the tournament system developed by novauniverse
version: 1.0
api-version: 1.13

authors: [Zeeraa, NovaUniverse]

depend: [NovaCore, DecentHolograms, ProtocolLib, TitleAPI, LuckPerms, Citizens, NoteBlockAPI, spark]
softdepend: [NovaCoreGameEngine, LabyApi, ItemsAdder, AdvancedGUI, CosmeticSystem, LabyApi]
loadbefore: [NovaGamesTarget, NovaSurvivalGames, ChickenOut]

permissions:
  tournamentsystem.staff:
    description: Indicates that the player is a staff member
    default: false