main: net.novauniverse.mctournamentsystem.spigot.TournamentSystem
name: TournamentSystem
description: The 5th version of the tournament system developed by novauniverse
version: 1.0
api-version: 1.13

depend: [NovaCore, HolographicDisplays, ProtocolLib, TitleAPI, LuckPerms]
softdepent: [NovaCoreGameEngine, LabyApi]
loadbefore: [NovaGamesTarget]